version: 2.1
orbs:
  coverage-reporter: codacy/coverage-reporter@12.1.0
jobs:
  build:
    docker:
      - image: circleci/node:12

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Bundle Install
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run Lint
          command: yarn eslint

      - run:
          name: Run test
          command: yarn test --coverage

      - store_test_results:
          path: coverage

      - store_artifacts:
          path: coverage

      - coverage-reporter/send_report:
          coverage-reports: 'clover.xml, lcov.info'
          project-token: 1e09603add1444d4b64c39aea667ee53

  deploy:
    machine:
      image: ubuntu-1604:202007-01

    steps:
      - run:
          command: curl -X POST -d {} ${deploy_endpoint}
  

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build

